service: data-processing-pipeline-service

provider:
  name: aws
  runtime: nodejs12.x

functions:
  processImage:
    handler: handler.processImage
    events:
      - http:
          path: processImage
          method: post

# resources:
#  Resources:
#    ImageInputBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: natasjas-image-input-bucket
#        CorsConfiguration:
#         CorsRules:
#           -
#             AllowedOrigins:
#               - '*'
#             AllowedHeaders:
#               - '*'
#             AllowedMethods:
#               - GET
#               - PUT
#               - POST
#               - DELETE
#               - HEAD
#             MaxAge: 3000

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
